//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Day01 {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IT_Day01.LanguageResources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 出生日 的當地語系化字串。
        /// </summary>
        internal static string Birthday_Day {
            get {
                return ResourceManager.GetString("Birthday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出生月 的當地語系化字串。
        /// </summary>
        internal static string Birthday_Month {
            get {
                return ResourceManager.GetString("Birthday_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出生年 的當地語系化字串。
        /// </summary>
        internal static string Birthday_Year {
            get {
                return ResourceManager.GetString("Birthday_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安安我想認識你，先做個自我介紹嗎 的當地語系化字串。
        /// </summary>
        internal static string FormStart {
            get {
                return ResourceManager.GetString("FormStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 家鄉 的當地語系化字串。
        /// </summary>
        internal static string HomeTown {
            get {
                return ResourceManager.GetString("HomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出生年月日請輸入數字 的當地語系化字串。
        /// </summary>
        internal static string Message_BirthdayNeedNum {
            get {
                return ResourceManager.GetString("Message_BirthdayNeedNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 哈囉,我的名子是{0}. 我是 {1} 人 , 目前 {2} 歲. 的當地語系化字串。
        /// </summary>
        internal static string Message_IntrouductionText {
            get {
                return ResourceManager.GetString("Message_IntrouductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇大頭照 的當地語系化字串。
        /// </summary>
        internal static string Message_NoImage {
            get {
                return ResourceManager.GetString("Message_NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入 {0} 的當地語系化字串。
        /// </summary>
        internal static string Message_PleaseInput {
            get {
                return ResourceManager.GetString("Message_PleaseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
    }
}
